export { runFinalReport } from "./service";
export type {
  FinalReportResult,
  QuickAnswer,
  BearBaseBull,
  BusinessQuality,
  ValuationSummary,
  WhatsHappeningNow,
  RecentDevelopment,
  MarketSentimentSummary,
  EconomySummary,
  CompetitionSummary,
  ManagementSummary,
  DevilsAdvocateSummary,
  WhatWouldChangeAiMind,
  FinalConclusion,
  ReportSource,
  DataConsistencyNote,
  QualityLabel,
} from "@/lib/final-report-types";
